version: "3.9"
services:
  auth_checker:
    build: .
    restart: on-failure
    command: python3 check.py
